name: Development Workflow

on:
  push:


jobs:
  lint:
    name: Lint Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: true # <- To avoid actually having to fix the linting issues :)

  build:
    name: Build Application (node)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
  dockerize:
    name: Build Application (docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t Henchway/DevOpsExercise1:latest .
        working-directory: ./app  # Change this to your app's directory

      - name: Push Docker Image
        run: docker push Henchway/DevOpsExercise1:latest

      - name: Logout from Docker Hub
        run: docker logout


